FROM alpine:3.18

RUN apk update && apk upgrade && \
    apk add --no-cache redis && \
    sed -i "s|bind 127.0.0.1|#bind 127.0.0.1|g"  /etc/redis.conf && \
    sed -i "s|# maxmemory <bytes>|maxmemory 20mb|g"  /etc/redis.conf && \
    echo "maxmemory-policy allkeys-lru" >> /etc/redis.conf
# Sets Redis to use a maximum of 20 megabytes of RAM.

EXPOSE 6379

CMD [ "redis-server" , "/etc/redis.conf" ]
